from datetime import date
from typing import Any, Protocol
from uuid import UUID

from app.domain.entities import (
    Customer,
    Device,
    DeviceModel,
    Installation,
    InventoryTransaction,
    Tenant,
    User,
)
from app.domain.enums import DeviceStatus
from app.domain.read_models import CountItem, DeviceView, InstallationView, TransactionView


class TenantRepository(Protocol):
    async def get(self, tenant_id: UUID) -> Tenant | None: ...
    async def get_by_code(self, code: str) -> Tenant | None: ...
    async def list(self) -> list[Tenant]: ...
    async def add(self, tenant: Tenant) -> None: ...
    async def update(self, tenant: Tenant) -> None: ...


class UserRepository(Protocol):
    async def get(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def list(self) -> list[User]: ...
    async def add(self, user: User) -> None: ...
    async def update(self, user: User) -> None: ...


class DeviceModelRepository(Protocol):
    async def get(self, model_id: UUID) -> DeviceModel | None: ...
    async def list(self) -> list[DeviceModel]: ...
    async def add(self, model: DeviceModel) -> None: ...
    async def update(self, model: DeviceModel) -> None: ...
    async def delete(self, model_id: UUID) -> None: ...
    async def is_in_use(self, model_id: UUID) -> bool: ...


class DeviceRepository(Protocol):
    async def get(self, device_id: UUID, *, for_update: bool = False) -> Device | None: ...
    async def get_by_serial(self, serial_number: str) -> Device | None: ...
    async def exists_serial(self, serial_number: str) -> bool: ...
    async def get_view(self, device_id: UUID) -> DeviceView | None: ...
    async def list_views(
        self,
        *,
        search: str | None = None,
        status: DeviceStatus | None = None,
        model_id: UUID | None = None,
    ) -> list[DeviceView]: ...
    async def add(self, device: Device) -> None: ...
    async def update(self, device: Device) -> None: ...
    async def count_by_status(self) -> list[CountItem]: ...
    async def count_by_model(self) -> list[CountItem]: ...
    async def warranty_expiring(self, until: date) -> list[DeviceView]: ...


class TransactionRepository(Protocol):
    async def add(self, tx: InventoryTransaction) -> None: ...
    async def list_views(self, *, device_id: UUID | None = None, limit: int = 500) -> list[TransactionView]: ...


class CustomerRepository(Protocol):
    async def get(self, customer_id: UUID) -> Customer | None: ...
    async def list(self) -> list[Customer]: ...
    async def add(self, customer: Customer) -> None: ...
    async def update(self, customer: Customer) -> None: ...
    async def delete(self, customer_id: UUID) -> None: ...
    async def has_installations(self, customer_id: UUID) -> bool: ...


class InstallationRepository(Protocol):
    async def get(self, installation_id: UUID) -> Installation | None: ...
    async def get_active_for_device(self, device_id: UUID) -> Installation | None: ...
    async def get_view(self, installation_id: UUID) -> InstallationView | None: ...
    async def list_views(self, *, active_only: bool = True) -> list[InstallationView]: ...
    async def nearby(self, latitude: float, longitude: float, radius_m: float) -> list[InstallationView]: ...
    async def add(self, installation: Installation) -> None: ...
    async def update(self, installation: Installation) -> None: ...


class UnitOfWork(Protocol):
    tenants: TenantRepository
    users: UserRepository
    device_models: DeviceModelRepository
    devices: DeviceRepository
    transactions: TransactionRepository
    customers: CustomerRepository
    installations: InstallationRepository

    async def flush(self) -> None: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password_hash: str, password: str) -> bool: ...


class TokenService(Protocol):
    def issue_access(self, claims: dict[str, Any]) -> str: ...
    def issue_refresh(self, claims: dict[str, Any]) -> str: ...
    def decode(self, token: str, *, expected_type: str) -> dict[str, Any]: ...


# Extension points for phase 2; no implementation yet.
class TelemetryPort(Protocol):
    async def record(self, device_id: UUID, metrics: dict[str, float]) -> None: ...
    async def mark_offline(self, device_id: UUID) -> None: ...


class IssueSummarizerPort(Protocol):
    async def summarize(self, issue_text: str) -> dict[str, Any]: ...
